spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sandbox
    username: postgres
    password: "020407"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
